/*
 * Name: Alec Farfan
 * Date: 03/20/15
 * Purpose: GUI for Matrix Calculator
 */

// Import libraries
import java.awt.Color.*;
import java.awt.*;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.util.Vector;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;

public class Matrix_Calculator_UI extends javax.swing.JFrame {

    Vector<JTable> table_array;
    public Matrix_Calculator_UI() {
        
        initComponents();
        getContentPane().setBackground(java.awt.Color.black);
        table_array = new Vector<JTable>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addition_button = new javax.swing.JButton();
        subtraction_button = new javax.swing.JButton();
        matrix_multiplication_button = new javax.swing.JButton();
        matrix_transpose_button = new javax.swing.JButton();
        scalar_multiplication_button = new javax.swing.JButton();
        matrix_inverse_button = new javax.swing.JButton();
        row_echelon_form_button = new javax.swing.JButton();
        determinant_button = new javax.swing.JButton();
        lu_factorization_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        reduced_row_echelon_button = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();

        jButton16.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        jButton16.setText("RANK");
        jButton16.setToolTipText("Rank");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrix Calculator");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 635));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Matrices");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 534, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        addition_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        addition_button.setText("U + V");
        addition_button.setToolTipText("Matrix Addition");
        addition_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addition_buttonActionPerformed(evt);
            }
        });

        subtraction_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        subtraction_button.setText("U - V");
        subtraction_button.setToolTipText("Matrix Subtraction");
        subtraction_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtraction_buttonActionPerformed(evt);
            }
        });

        matrix_multiplication_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        matrix_multiplication_button.setText("U x V");
        matrix_multiplication_button.setToolTipText("Matrix Multiplication");
        matrix_multiplication_button.setMaximumSize(new java.awt.Dimension(55, 21));
        matrix_multiplication_button.setMinimumSize(new java.awt.Dimension(55, 21));
        matrix_multiplication_button.setPreferredSize(new java.awt.Dimension(55, 21));
        matrix_multiplication_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrix_multiplication_buttonActionPerformed(evt);
            }
        });

        matrix_transpose_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        matrix_transpose_button.setText("<html>U<sup> T</sup></html>");
        matrix_transpose_button.setToolTipText("Matrix Transpose");
        matrix_transpose_button.setMaximumSize(new java.awt.Dimension(55, 21));
        matrix_transpose_button.setMinimumSize(new java.awt.Dimension(55, 21));
        matrix_transpose_button.setPreferredSize(new java.awt.Dimension(55, 21));
        matrix_transpose_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrix_transpose_buttonActionPerformed(evt);
            }
        });

        scalar_multiplication_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        scalar_multiplication_button.setText("cU");
        scalar_multiplication_button.setToolTipText("Scalar Multiplication");
        scalar_multiplication_button.setBorder(null);
        scalar_multiplication_button.setMaximumSize(new java.awt.Dimension(55, 21));
        scalar_multiplication_button.setMinimumSize(new java.awt.Dimension(55, 21));
        scalar_multiplication_button.setPreferredSize(new java.awt.Dimension(55, 21));
        scalar_multiplication_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scalar_multiplication_buttonActionPerformed(evt);
            }
        });

        matrix_inverse_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        matrix_inverse_button.setText("<html>U<sup> -1</sup></html>");
        matrix_inverse_button.setToolTipText("Matrix Inverse");
        matrix_inverse_button.setMaximumSize(new java.awt.Dimension(55, 21));
        matrix_inverse_button.setMinimumSize(new java.awt.Dimension(55, 21));
        matrix_inverse_button.setPreferredSize(new java.awt.Dimension(55, 21));
        matrix_inverse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrix_inverse_buttonActionPerformed(evt);
            }
        });

        row_echelon_form_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        row_echelon_form_button.setText("REF");
        row_echelon_form_button.setToolTipText("Row Echelon Form");
        row_echelon_form_button.setMaximumSize(new java.awt.Dimension(55, 21));
        row_echelon_form_button.setMinimumSize(new java.awt.Dimension(55, 21));
        row_echelon_form_button.setPreferredSize(new java.awt.Dimension(55, 21));
        row_echelon_form_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                row_echelon_form_buttonActionPerformed(evt);
            }
        });

        determinant_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        determinant_button.setText("DET");
        determinant_button.setToolTipText("Determinant");
        determinant_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determinant_buttonActionPerformed(evt);
            }
        });

        lu_factorization_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        lu_factorization_button.setText("LU");
        lu_factorization_button.setToolTipText("LU Factorization");
        lu_factorization_button.setMaximumSize(new java.awt.Dimension(55, 21));
        lu_factorization_button.setMinimumSize(new java.awt.Dimension(55, 21));
        lu_factorization_button.setPreferredSize(new java.awt.Dimension(55, 21));
        lu_factorization_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lu_factorization_buttonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Expression");

        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jButton12.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton12.setText("Enter");

        jButton14.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton14.setText("Clear");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton14))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton13.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton13.setText("Clear");

        reduced_row_echelon_button.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        reduced_row_echelon_button.setText("RREF");
        reduced_row_echelon_button.setToolTipText("Reduced Row Echelon Form");
        reduced_row_echelon_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reduced_row_echelon_buttonActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton18.setText("Remove");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addition_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtraction_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrix_multiplication_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scalar_multiplication_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row_echelon_form_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reduced_row_echelon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(determinant_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lu_factorization_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matrix_transpose_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrix_inverse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addition_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row_echelon_form_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtraction_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reduced_row_echelon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrix_multiplication_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(determinant_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scalar_multiplication_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lu_factorization_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matrix_transpose_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matrix_inverse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton18))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel6.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Steps of Computation");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(jLabel6);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jTextField1.setSelectedTextColor(new java.awt.Color(102, 255, 102));
        jTextField1.setSelectionColor(new java.awt.Color(102, 255, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setSelectionColor(new java.awt.Color(102, 255, 102));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("m");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("n");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");

        jButton4.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton4.setText("Create New m x n Matrix");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("                                                     Result of Computation");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(179, 114));

        jButton17.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton17.setText("Add to Matrices List");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(179, 114));

        jButton19.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        jButton19.setText("Save Computation");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton19)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jScrollPane1.getViewport().setBackground(java.awt.Color.black);
        jScrollPane2.getViewport().setBackground(java.awt.Color.white);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addition_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addition_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable a = table_array.get(0);
        JTable b = table_array.get(1);
        
        int m = a.getRowCount();
        int n = a.getColumnCount();
        Matrix matrix_a = new Matrix(m,n);
        Matrix matrix_b = new Matrix(m,n);
        
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(a.getValueAt(i,j)!=null){
                    matrix_a.set_element(Float.parseFloat(a.getValueAt(i,j).toString()),i,j);
                    matrix_b.set_element(Float.parseFloat(b.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        Matrix result = matrix_a.matrix_addition(matrix_a,matrix_b);
        jLabel9.setText(result.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_addition_buttonActionPerformed

    private void subtraction_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtraction_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable a = table_array.get(0);
        JTable b = table_array.get(1);
        
        int m = a.getRowCount();
        int n = a.getColumnCount();
        Matrix matrix_a = new Matrix(m,n);
        Matrix matrix_b = new Matrix(m,n);
        
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(a.getValueAt(i,j)!=null){
                    matrix_a.set_element(Float.parseFloat(a.getValueAt(i,j).toString()),i,j);
                    matrix_b.set_element(Float.parseFloat(b.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        Matrix result = matrix_a.matrix_subtraction(matrix_a,matrix_b);
        jLabel9.setText(result.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_subtraction_buttonActionPerformed

    private void matrix_multiplication_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrix_multiplication_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable a = table_array.get(0);
        JTable b = table_array.get(1);
        
        int m = a.getRowCount();
        int n = a.getColumnCount();
        Matrix matrix_a = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(a.getValueAt(i,j)!=null){
                    matrix_a.set_element(Float.parseFloat(a.getValueAt(i,j).toString()),i,j);
                }
            }
        } 
        m = b.getRowCount();
        n = b.getColumnCount();
        Matrix matrix_b = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(b.getValueAt(i,j)!=null){
                    matrix_b.set_element(Float.parseFloat(b.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        
        Matrix result = matrix_a.matrix_multiplication(matrix_a,matrix_b);
        jLabel9.setText(result.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate(); 
    }//GEN-LAST:event_matrix_multiplication_buttonActionPerformed

    private void matrix_transpose_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrix_transpose_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        new_matrix = new_matrix.matrix_transpose(new_matrix);
        jLabel9.setText(new_matrix.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_matrix_transpose_buttonActionPerformed

    private void scalar_multiplication_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scalar_multiplication_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        new_matrix = new_matrix.scalar_multiplication(new_matrix,2);
        jLabel9.setText(new_matrix.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_scalar_multiplication_buttonActionPerformed

    private void matrix_inverse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrix_inverse_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        new_matrix = new_matrix.matrix_inverse(new_matrix);
        jLabel9.setText(new_matrix.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_matrix_inverse_buttonActionPerformed

    private void row_echelon_form_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_row_echelon_form_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        new_matrix = new_matrix.row_echelon_form(new_matrix);
        jLabel9.setText(new_matrix.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
        
    }//GEN-LAST:event_row_echelon_form_buttonActionPerformed

    private void determinant_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determinant_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_determinant_buttonActionPerformed

    private void lu_factorization_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lu_factorization_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        ArrayList<Matrix> result = new_matrix.lu_decompisition(new_matrix);
        String print_string[] = new String[2];
        for(int i=0;i<result.size();i++){
            print_string[i] = result.get(i).println();
        }
        jLabel9.setText(print_string[0]);
        jLabel9.setVisible(true);
        jLabel8.setText(print_string[1]);
        jLabel8.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_lu_factorization_buttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void reduced_row_echelon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reduced_row_echelon_buttonActionPerformed
        jLabel8.setVisible(false);
        JTable selected = table_array.get(0);
        int m = selected.getRowCount();
        int n = selected.getColumnCount();
        Matrix new_matrix = new Matrix(m,n);
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(selected.getValueAt(i,j)!=null){
                    new_matrix.set_element(Float.parseFloat(selected.getValueAt(i,j).toString()),i,j);
                }
            }
        }
        new_matrix = new_matrix.reduced_row_echelon_form(new_matrix);
        jLabel9.setText(new_matrix.println());
        jLabel9.setVisible(true);
        jPanel4.revalidate();
        revalidate();
    }//GEN-LAST:event_reduced_row_echelon_buttonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        int m = Integer.parseInt(jTextField1.getText());
        int n = Integer.parseInt(jTextField2.getText());
        JTable new_table = new JTable(m,n);
        TableColumnModel column = new_table.getColumnModel();
        for(int i=0;i<n;i++){
            column.getColumn(i).setPreferredWidth(20);
        }
        new_table.setGridColor(Color.BLACK);
        new_table.setShowGrid(true);
        table_array.add(new_table);
        jScrollPane1.remove(jPanel6);
        jPanel6 = new JPanel();
        jPanel6.setLayout(new BoxLayout(jPanel6,BoxLayout.Y_AXIS));
        jPanel6.setBackground(Color.BLACK);
        
        jPanel6.add(jLabel7);
        for(int i=0;i<table_array.size();i++){
            jPanel6.add(table_array.get(i));
            jPanel6.add(Box.createVerticalStrut(5));
        }
        jScrollPane1.getViewport().add(jPanel6);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame plane = new JFrame("Matrix Calculator");
                plane.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                Matrix_Splash test = new Matrix_Splash();
                plane.add(test);
                plane.setSize(1100,635);
                plane.setVisible(true);
                //new Matrix_Calculator_UI();//.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addition_button;
    private javax.swing.JButton determinant_button;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton lu_factorization_button;
    private javax.swing.JButton matrix_inverse_button;
    private javax.swing.JButton matrix_multiplication_button;
    private javax.swing.JButton matrix_transpose_button;
    private javax.swing.JButton reduced_row_echelon_button;
    private javax.swing.JButton row_echelon_form_button;
    private javax.swing.JButton scalar_multiplication_button;
    private javax.swing.JButton subtraction_button;
    // End of variables declaration//GEN-END:variables
}
